spring.application.name=MiniKintusgi

spring.datasource.url=jdbc:postgresql://localhost:5432/minikintsugi

spring.datasource.username=postgres

spring.datasource.password=Naughtystone999*

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
